# Generated by Django 5.0.7 on 2024-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('unit', models.CharField(choices=[('pcs', 'Штук'), ('blk', 'Блок')], default='pcs', max_length=3, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Сироп',
                'verbose_name_plural': 'Сиропы',
            },
        ),
    ]
